steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/anime_quote_app_repo/anime_quote_app_image",
        ".",
      ]
images: ["gcr.io/$PROJECT_ID/anime_quote_app_repo/anime_quote_app_image"]
