apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-quote-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime-quote-app
  template:
    metadata:
      labels:
        app: anime-quote-app
    spec:
      containers:
        - name: anime-quote-app-container
          image: gcr.io/anime_quote_app_repo/anime_quote_app_image:latest
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: anime-quote-app-service
  namespace: gke-gcp-devops-prod
spec:
  selector:
    app: anime-quote-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
